### ISSUE TITLE
UNKNOWN: ArrayExpression

### ISSUE THREAD

**Issue by ghost** [ozten/fmt.js#1]
Suppose I have a file:

``` js
// hello.js
var hello = ['a', 'b', 'c'];
```

When I call `fmtjs hello.js` I get the following:

```
UNKNOWN: ArrayExpression
var hello = undefined;
```

**Comment by ozten** [comment]
I'm using [js-beautify](https://github.com/beautify-web/js-beautify) these days.

**Comment by ghost** [comment]
Oh, cool.
